AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Finance Tracker 2.0 - Enhanced FastAPI Application'

Parameters:
  TelegramBotToken:
    Type: String
    Description: Telegram Bot Token for notifications
    NoEcho: true

  TelegramChatId:
    Type: String
    Description: Telegram Chat ID for notifications
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    Environment:
      Variables:
        TRANSACTIONS_TABLE: !Ref TransactionsTable
        CATEGORIES_TABLE: !Ref CategoriesTable
        RECURRING_TABLE: !Ref RecurringTable

Resources:
  # DynamoDB Tables
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FinanceTracker-Transactions
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: transaction_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: transaction_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FinanceTracker-Categories
      AttributeDefinitions:
        - AttributeName: category_id
          AttributeType: S
      KeySchema:
        - AttributeName: category_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RecurringTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FinanceTracker-Recurring
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: recurring_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: recurring_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # Main FastAPI Lambda Function
  FinanceTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: handler.handler
      Runtime: python3.11
      Environment:
        Variables:
          TRANSACTIONS_TABLE: !Ref TransactionsTable
          CATEGORIES_TABLE: !Ref CategoriesTable
          RECURRING_TABLE: !Ref RecurringTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CategoriesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RecurringTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

  # Recurring Transaction Processor
  RecurringProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../sam-backend/handlers/
      Handler: recurring_processor.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          RECURRING_TABLE: !Ref RecurringTable
          TRANSACTIONS_TABLE: !Ref TransactionsTable
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_CHAT_ID: !Ref TelegramChatId
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RecurringTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
      Events:
        # Run daily at 6 AM UTC
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
            Description: "Process recurring transactions daily"
        
        # Run weekly on Mondays at 6 AM UTC
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 ? * MON *)
            Description: "Process weekly recurring transactions"
        
        # Run monthly on the 1st at 6 AM UTC
        MonthlySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 1 * ? *)
            Description: "Process monthly recurring transactions"

Outputs:
  FinanceTrackerApi:
    Description: "API Gateway endpoint URL for Finance Tracker"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FinanceTrackerFunction:
    Description: "Finance Tracker Lambda Function ARN"
    Value: !GetAtt FinanceTrackerFunction.Arn